on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: ChatGPT explain code
    steps:
      - name: ChatGTP explain code
        uses: ./
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: "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"
          github_commit_id: ${{ github.event.push_id }}
          openai_engine: "text-davinci-002" #optional
          openai_temperature: 0.5 #optional
          openai_max_tokens: 2048 #optional